config/routes.rb
# == Route Map
#
#                                Prefix Verb     URI Pattern                                  Controller#Action
#      user_facebook_omniauth_authorize GET|POST /users/auth/facebook(.:format)               auth/omniauth_callbacks#passthru
#       user_facebook_omniauth_callback GET|POST /users/auth/facebook/callback(.:format)      auth/omniauth_callbacks#facebook
# user_google_oauth2_omniauth_authorize GET|POST /users/auth/google_oauth2(.:format)          auth/omniauth_callbacks#passthru
#  user_google_oauth2_omniauth_callback GET|POST /users/auth/google_oauth2/callback(.:format) auth/omniauth_callbacks#google_oauth2
#                                logout DELETE   /logout(.:format)                            devise/sessions#destroy
#                            categories GET      /categories(.:format)                        categories#index
#                                       POST     /categories(.:format)                        categories#create
#                          new_category GET      /categories/new(.:format)                    categories#new
#                         edit_category GET      /categories/:id/edit(.:format)               categories#edit
#                              category PATCH    /categories/:id(.:format)                    categories#update
#                                       PUT      /categories/:id(.:format)                    categories#update
#                                       DELETE   /categories/:id(.:format)                    categories#destroy
#                                  root GET      /                                            welcome#home
#                   edit_images_product GET      /products/:id/edit_images(.:format)          products#edit_images
#                    add_images_product POST     /products/:id/add_images(.:format)           products#add_images
#                destroy_images_product POST     /products/:id/destroy_images(.:format)       products#destroy_images
#                              products POST     /products(.:format)                          products#create
#                           new_product GET      /products/new(.:format)                      products#new
#                          edit_product GET      /products/:id/edit(.:format)                 products#edit
#                               product GET      /products/:id(.:format)                      products#show
#                                       PATCH    /products/:id(.:format)                      products#update
#                                       PUT      /products/:id(.:format)                      products#update
#                                       DELETE   /products/:id(.:format)                      products#destroy
#                               western GET      /western(.:format)                           products#western_index
#                                ethnic GET      /ethnic(.:format)                            products#ethnic_index
#                       admin_dashboard GET      /admin_dashboard(.:format)                   welcome#admin_dashboard
#              cart_show_without_layout POST     /cart/show_without_layout(.:format)          cart#show_without_layout
#                             cart_show GET      /cart/show(.:format)                         cart#show
#                         cart_add_item POST     /cart/add_item(.:format)                     cart#add_item
#                      cart_remove_item POST     /cart/remove_item(.:format)                  cart#remove_item
#                       cart_empty_cart POST     /cart/empty_cart(.:format)                   cart#empty_cart
#

Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "auth/omniauth_callbacks" }, :skip => [:sessions, :passwords, :registrations]
  devise_scope :user do
    delete "/logout" => "devise/sessions#destroy"
  end
  resources :categories, except: :show
  root 'welcome#home'
  resources :products, except: :index do
    member do
      get 'edit_images'
      post 'add_images'
      post 'destroy_images'
    end
  end
  get 'western', to: 'products#western_index'
  get 'ethnic', to: 'products#ethnic_index'
  get 'admin_dashboard', to: 'welcome#admin_dashboard'
  post 'cart/show_without_layout'
  get 'cart/show'
  post 'cart/add_item'
  post 'cart/remove_item'
  post 'cart/empty_cart'

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def show_without_layout
    @cart = get_shopping_cart
    render layout: false
  end

  def show
    @cart = get_shopping_cart
  end

  def add_item
    product = Product.find(params[:product_id])
    @cart_item = get_shopping_cart.add_item(product, cart_params)
    if @cart_item.valid?
      render 'item_added', layout: false
    else
      render 'item_not_added', layout: false
    end
  end

  def remove_item
    product = Product.find(params[:product_id])
    get_shopping_cart.remove_item(product)
    render layout: false
  end

  def empty_cart
    get_shopping_cart.empty_cart
    render status: 200
  end

  private

    def cart_params
      params.require(:cart).permit(:product_id, :delivery_date, :delivery_time, :size)
    end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/item_added.js.erb
$('.cart-error').html('');
$.post('/cart/show_without_layout.html', function(data, status){
	$('#cart-dropdown').html(data);
});
Materialize.toast('Cart Updated!', 1000);

app/views/cart/item_not_added.js.erb
$('.cart-error#size_error').html("<%= @cart_item.errors.full_messages_for(:size)[0] %>");
$('.cart-error#delivery_date_error').html("<%= @cart_item.errors.full_messages_for(:delivery_date)[0] %>");
$('.cart-error#delivery_time_error').html("<%= @cart_item.errors.full_messages_for(:delivery_time)[0] %>");

app/views/cart/remove_item.js.erb
$.post('/cart/show_without_layout.html', function(data, status){
	$('#cart-dropdown').html(data);
});
Materialize.toast('Cart Updated!', 1000)

app/views/cart/show_without_layout.html.erb
<% if @cart.item_count > 0 %>
  <div class="cart-container">
    <h5>Your Cart ( <%= pluralize(@cart.item_count, "Item") %> )</h5>
    <% @cart.shopping_cart_items.each do |cart_item| %>
      <div class="row">
        <div class="col s4">
          <% product = cart_item.product %>
          <%= image_tag(product.product_images.first.image_url, width: '100%') %>
        </div>
        <div class="col s8">
          <h6><%= product.name %></h6>
          <%= link_to("x", cart_remove_item_path(product_id: product.id), remote: true, class: 'right btn', method: :post) %>
          <h6>Rent: <%= cart_item.price %></h6>
          <h6>Size: <%= cart_item.size %></h6>
          <h6>Delivery Date: <%= cart_item.delivery_date %></h6>
          <h6>Delivery Time: <%= cart_item.delivery_time %></h6>
        </div>
      </div>
      <hr>
    <% end %>
    <h5>Total: <%= @cart.total %></h5>
  </div>
<% else %>
  No Items Yet.
<% end %>