config/routes.rb
# == Route Map
#
#                                Prefix Verb     URI Pattern                                  Controller#Action
#      user_facebook_omniauth_authorize GET|POST /users/auth/facebook(.:format)               auth/omniauth_callbacks#passthru
#       user_facebook_omniauth_callback GET|POST /users/auth/facebook/callback(.:format)      auth/omniauth_callbacks#facebook
# user_google_oauth2_omniauth_authorize GET|POST /users/auth/google_oauth2(.:format)          auth/omniauth_callbacks#passthru
#  user_google_oauth2_omniauth_callback GET|POST /users/auth/google_oauth2/callback(.:format) auth/omniauth_callbacks#google_oauth2
#                                logout DELETE   /logout(.:format)                            devise/sessions#destroy
#                            categories GET      /categories(.:format)                        categories#index
#                                       POST     /categories(.:format)                        categories#create
#                          new_category GET      /categories/new(.:format)                    categories#new
#                         edit_category GET      /categories/:id/edit(.:format)               categories#edit
#                              category PATCH    /categories/:id(.:format)                    categories#update
#                                       PUT      /categories/:id(.:format)                    categories#update
#                                       DELETE   /categories/:id(.:format)                    categories#destroy
#                                  root GET      /                                            welcome#home
#                   edit_images_product GET      /products/:id/edit_images(.:format)          products#edit_images
#                    add_images_product POST     /products/:id/add_images(.:format)           products#add_images
#                destroy_images_product POST     /products/:id/destroy_images(.:format)       products#destroy_images
#                              products POST     /products(.:format)                          products#create
#                           new_product GET      /products/new(.:format)                      products#new
#                          edit_product GET      /products/:id/edit(.:format)                 products#edit
#                               product GET      /products/:id(.:format)                      products#show
#                                       PATCH    /products/:id(.:format)                      products#update
#                                       PUT      /products/:id(.:format)                      products#update
#                                       DELETE   /products/:id(.:format)                      products#destroy
#                               western GET      /western(.:format)                           products#western_index
#                                ethnic GET      /ethnic(.:format)                            products#ethnic_index
#                       admin_dashboard GET      /admin_dashboard(.:format)                   welcome#admin_dashboard
#              cart_show_without_layout POST     /cart/show_without_layout(.:format)          cart#show_without_layout
#                             cart_show GET      /cart/show(.:format)                         cart#show
#                         cart_add_item POST     /cart/add_item(.:format)                     cart#add_item
#                      cart_remove_item POST     /cart/remove_item(.:format)                  cart#remove_item
#                       cart_empty_cart POST     /cart/empty_cart(.:format)                   cart#empty_cart
#

Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "auth/omniauth_callbacks" }, :skip => [:sessions, :passwords, :registrations]
  devise_scope :user do
    delete "/logout" => "devise/sessions#destroy"
  end
  resources :categories, except: :show
  root 'welcome#home'
  resources :products, except: :index do
    member do
      get 'edit_images'
      post 'add_images'
      post 'destroy_images'
    end
  end
  get 'western', to: 'products#western_index'
  get 'ethnic', to: 'products#ethnic_index'
  get 'admin_dashboard', to: 'welcome#admin_dashboard'
  post 'cart/show_without_layout'
  get 'cart/show'
  post 'cart/add_item'
  post 'cart/remove_item'
  post 'cart/empty_cart'

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id            :integer          not null, primary key
#  name          :string
#  rent_price    :integer
#  actual_price  :integer
#  description   :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  supercategory :string
#  sizes         :string           default([]), is an Array
#

class Product < ActiveRecord::Base
  has_many :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images
  has_many :product_categories, dependent: :destroy
  accepts_nested_attributes_for :product_categories
  has_many :categories, through: :product_categories

  SUPERCATEGORIES = [ 'Western', 'Ethnic' ]
  SIZES = [ 'S', 'M', 'L', 'XL' ]

  validates_presence_of :name
  validates :rent_price, numericality: { greater_than: 0, integer: true }
  validates :actual_price, numericality: { greater_than: 0, integer: true }
  validates :supercategory, inclusion: { in: SUPERCATEGORIES }
  validate :at_least_one_size_is_available
  validate :valid_sizes_array
  validate :at_least_one_image

  private

    def at_least_one_size_is_available
      unless sizes.is_a?(Array) && sizes.length > 0
        errors.add(:sizes, 'at least one size must be available')
      end
    end

    def valid_sizes_array
      if sizes.detect{|s| !SIZES.include?(s)}
        errors.add(:sizes, :invalid)
      end
    end

    def at_least_one_image
      if self.product_images.empty?
        errors.add('product_images.base', 'at least one image must be present')
      end
    end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authorize_only_admins, except: [ :western_index, :ethnic_index, :show ]

  def western_index
    @categories = Category.joins(:products).where('products.supercategory' => 'Western').distinct
    @products = Product.where('supercategory' => 'Western').distinct
    if params[:filters]
      if filter_params[:range_min] && filter_params[:range_max]
        @products = @products.where('rent_price >= ?', filter_params[:range_min]).where('rent_price <= ?', filter_params[:range_max])
      end
      if filter_params[:categories]
        @products = @products.where('id IN (SELECT product_categories.product_id FROM product_categories WHERE category_id IN (?) GROUP BY product_id HAVING COUNT(DISTINCT category_id) = ?)', filter_params[:categories], filter_params[:categories].length)
      end
      if filter_params[:sizes]
        @products = @products.where("sizes @> ARRAY[?]::varchar[]", filter_params[:sizes])
      end
      if params[:sort] == "low"
        @products = @products.order(:rent_price)
      end
      if params[:sort] == "high"
        @products = @products.order(rent_price: :desc)
      end
    end
    render 'index'
    # Product.where("sizes @> ARRAY[?]::varchar[]", ['S', 'M'])
  end

  def ethnic_index
    @categories = Category.joins(:products).where('products.supercategory' => 'Ethnic').distinct
    @products = Product.where('supercategory' => 'Ethnic')
    render 'index'
  end

  def edit
    @product = Product.find(params[:id])
  end

  def edit_images
    @product = Product.find(params[:id])
  end

  def destroy_images
    @product = Product.find(params[:id])
    if params[:product_images_ids].length >= @product.product_images.count
      redirect_to edit_images_product_url, notice: 'You cannot delete all the images.'
    else
      if @product.product_images.where(id: params[:product_images_ids]).destroy_all
        redirect_to edit_images_product_url, notice: 'Images were successfully deleted.'
      else
        redirect_to edit_images_product_url, notice: 'Images were NOT successfully deleted.'
      end
    end
  end

  def add_images
    @product = Product.find(params[:id])
    begin
      params['product_images'].reject(&:blank?).each do |image|
        @product.product_images.create!(image: image)
      end
      redirect_to edit_images_product_url, notice: 'Images were successfully added.'
    rescue
      redirect_to edit_images_product_url, notice: 'There was an error while adding images.'
    end
  end

  def show
    @product = Product.find(params[:id])
    @product_images = @product.product_images.all
    @cart_item = get_shopping_cart.shopping_cart_items.where(product: @product).first_or_initialize
  end

  def new
    @product = Product.new
    @product.product_images.build
  end

  def create
    @product = Product.new(product_params)
    begin
      params['product_images']['image'].compact.each do |image|
        @product.product_images.build(image: image)
      end
    rescue NoMethodError
    end
    begin
      params['product_categories']['category_id'].each do |cid|
        category = Category.find(cid)
        @product.product_categories.build(category: category)
      end
    rescue NoMethodError
    end

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
      else
        @product.product_images.destroy_all
        @product.product_images.build
        format.html { render action: 'new' }
      end
    end
  end

  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(product_params)
        @product.product_categories.destroy_all
        begin
          params['product_categories']['category_id'].each do |cid|
            category = Category.find(cid)
            @product.product_categories.create(category: category)
          end
        rescue NoMethodError
        end
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
      else
        format.html { render action: 'edit', notice: 'Product could not be updated.' }
      end
    end
  end

  private
     def product_params
        params.require(:product).permit(:name, :rent_price, :actual_price, :description, :supercategory, product_images_attributes: [ :image ], sizes: [], product_categories_attributes: [ :category_id ])
     end

     def filter_params
       params.require(:filters).permit(:range_min, :range_max, :sort, categories: [], sizes: [])
     end

     def authorize_only_admins
      authorize(Product, :is_admin?)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_filters.html.erb
<%= form_tag(request.path, method: :get, id: 'filter_form') do %>
  
  
  <ul class="collapsible" data-collapsible="expandable">
    <li>
      <div class="collapsible-header active">Category</div>
      <div class="collapsible-body">
        <% @categories.each do |category| %>
            <input type="checkbox" id="<%= category.id %>" value="<%= category.id %>" name="filters[categories][]" <%= "checked" if params[:filters] and params[:filters][:categories] and params[:filters][:categories].include?(category.id.to_s) %> />
            <label for="<%= category.id %>" class="filter-label"><%= category.name %></label>
            <br>
        <% end %>
      </div>
    </li>
    <li>
      <div class="collapsible-header active">Size</div>
      <div class="collapsible-body">
        <% Product::SIZES.each do |size| %>
            <input type="checkbox" id="<%= size %>" value="<%= size %>" name="filters[sizes][]" <%= "checked" if params[:filters] and params[:filters][:sizes] and params[:filters][:sizes].include?(size) %> />
            <label for="<%= size %>" class="filter-label"><%= size %></label>
            <br>
        <% end %>
      </div>
    </li>
    <li>
      <div class="collapsible-header active">Price</div>
      <div class="collapsible-body" id="slider-expandible">
        <div id="range"></div>
        <br>
        <div class="row">
          <div class="input-field col s5">
            <label for="range_min" class="active">From</label>
            <input id="range_min" type="text" name="filters[range_min]" 
            value="<%= params[:filters] ? params[:filters][:range_min] : 0 %>" readonly>
          </div>
          <div class="input-field col s5">
            <label for="range_max" class="active">To</label>
            <input id="range_max" type="text" name="filters[range_max]" value="<%= params[:filters] ? params[:filters][:range_max] : 2000 %>" readonly>
          </div>
        </div>         
      </div>
    </li>
  </ul>

  <%= submit_tag('Apply Filters', class: 'waves-effect waves-light btn') %>   
<% end %>

app/views/products/_product.html.erb
<div class="product-wrapper">
  <%= link_to(image_tag(product.product_images.first.image_url, class: 'index-image', alt: ' '), product) %>
  <h5><%= product.name %></h5>
  <span class="left">Rent: <%= product.rent_price %></span>
  <span class="right">Cost: <%= product.actual_price %></span>
</div>

app/views/products/edit.html.erb
<div class="container">
  <div class="row">
    <%= simple_form_for(@product, html: { class: 'col s12 m10 l8 offset-m1 offset-l2' }) do |f| %>

      <h3>New Product</h3> <br>

      <%= f.input :name, required: false %><br>

      <%= f.input :rent_price, required: false %><br>

      <%= f.input :actual_price, required: false %><br>

      <div class="input-field">
        <%= f.input_field :supercategory, collection: Product::SUPERCATEGORIES, wrapper_html: { class: 'input-field' }, include_blank: false %>
        <%= f.label :supercategory %> 
        <%= f.error :supercategory %> 
      </div> <br>
      
      <%= f.label :sizes %>
      <% Product::SIZES.each do |size| %>
        <p>
          <input type="checkbox" name="product[sizes][]" id="<%= size %>" value="<%= size %>" checked />
          <label for="<%= size %>"><%= size %></label>
        </p>
      <% end %> 
      <%= f.error :sizes %>
      <br><br>

      <%= f.input :description, wrapper_html: { class: 'input-field' }, input_html: { class: 'materialize-textarea' } %>
      <br>

      <label>Categories</label>
      <select name="product_categories[category_id][]" multiple>
        <option value="" disabled selected>Choose all applicable categories</option>
        <% Category.find_each do |category| %>
          <option value="<%= category.id %>" <%= @product.product_categories.where(category_id: category.id).exists? ? 'selected' : '' %>><%= category.name %></option>
        <% end %>
      </select>
      <br><br>

      <%= f.submit %>
    <% end %>
  </div>

<br><br>
  <%= link_to("Back to product", @product, class: 'waves-effect waves-light btn') %>

</div>

app/views/products/edit_images.html.erb
<br><br>
<div class="container">
   <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header">Delete Images</div>
      <div class="collapsible-body">
        <%= form_tag(destroy_images_product_path) do %>
          <% @product.product_images.each do |i| %>
            <div class="edit-image-wrapper">
              <input type="checkbox" name="product_images_ids[]" id="<%= i.id %>" value="<%= i.id %>" />
              <label for="<%= i.id %>" class="destroy-image-label"><%= image_tag(i.image_url, width: 200) %></label>
            </div>
          <% end %>
          <br><br>
          <%= submit_tag('Delete these images', class: 'waves-effect waves-light btn') %>
        <% end %>
        <br>
      </div>
    </li>
    <li>
      <div class="collapsible-header">Add new Images</div>
      <div class="collapsible-body">
        <%= form_tag(add_images_product_path, multipart: true) do %>
          <div class="file-field input-field">
            <div class="btn">
              <span>File</span>
              <input type="file" name="product_images[]" multiple>
            </div>
            <div class="file-path-wrapper">
              <input class="file-path validate" type="text" placeholder="Upload one or more images">
            </div>
          </div>
        <%= submit_tag('Upload Images', class: 'waves-effect waves-light btn') %>
        <% end %>
        <br>
      </div>
    </li>
  </ul>
  
  <br><br>
  <%= link_to("Back to product", @product, class: 'waves-effect waves-light btn') %>

</div>

app/views/products/index.html.erb
<div class="row" id="product-index-wrapper">
  <div class="col l3 m5 hide-on-small-only">
    <h5> Filters </h5>
    <%= render 'filters' %>
  </div>
  <div class="col l9 m7">
    <% if @products.empty? %>
      No Results.
    <% else %>
      <div class="row">
        <div id="sort" class="input-field col s8 m6 l4 right">
          <select name="sort" class="auto-submit-input" form='filter_form'>
            <option value="popular" <%= 'selected' if params[:sort] != "high" && params[:sort] != "low" %>>Popularity</option>
            <option value="high" <%= 'selected' if params[:sort] == "high" %>>Price: High to Low</option>
            <option value="low" <%= 'selected' if params[:sort] == "low" %>>Price: Low to High</option>
          </select>
        </div>
      </div>  
      <%= render @products %>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="row">
  <div class="col s6 m4 l3">
    <%= render 'welcome/sidenav' %>
  </div>
  <div class="col s6 m8 l9">
    <%= simple_form_for(@product, html: { multipart: true, class: 'col s12 m10 l8 offset-m1 offset-l1' }) do |f| %>

      <h3>New Product</h3> <br>

      <%= f.input :name, required: false %><br>

      <%= f.input :rent_price, required: false %><br>

      <%= f.input :actual_price, required: false %><br>

      <div class="input-field">
        <%= f.input_field :supercategory, collection: Product::SUPERCATEGORIES, wrapper_html: { class: 'input-field' }, include_blank: false %>
        <%= f.label :supercategory %> 
        <%= f.error :supercategory %> 
      </div> <br>
      
      <%= f.label :sizes %>
      <% Product::SIZES.each do |size| %>
        <p>
          <input type="checkbox" name="product[sizes][]" id="<%= size %>" value="<%= size %>" checked />
          <label for="<%= size %>"><%= size %></label>
        </p>
      <% end %> 
      <%= f.error :sizes %>
      <br><br>

      <%= f.input :description, wrapper_html: { class: 'input-field' }, input_html: { class: 'materialize-textarea' } %>
      <br>

      <%= f.simple_fields_for(:product_images) do |ff| %>
        <%= ff.input :image, input_html: { multiple: true, name: "product_images[image][]" }, label: 'Images <br>'.html_safe %>
      <% end %> <br>
      <%= f.error 'product_images.base' %>
      <br><br>

      <label>Categories</label>
      <select name="product_categories[category_id][]" multiple>
        <option value="" disabled selected>Choose all applicable categories</option>
        <% Category.find_each do |category| %>
          <option value="<%= category.id %>"><%= category.name %></option>
        <% end %>
      </select>
      <br><br>

      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col s6">
      <div class="product-images-slider">
        <% @product_images.each do |i| %>
          <div>
            <img src="<%= i.image_url %>" class="product-image">
          </div>
        <% end %>
      </div>
    </div>
    <div class="col s6 center-align" id="product-info">
      <h5 class="center-align"> <%= @product.name %> </h5>
      Rent Price: <%= @product.rent_price %> <br>
      Actual Price: <%= @product.actual_price %> <br>
      Sizes Available: <span id="sizes"><%= @product.sizes.join(", ") %></span>
      <br><br>
      Categories: 
      <% @product.categories.each do |category| %>
        <div class="chip"><%= category.name %></div>
      <% end %>
      <br><br>
      <span id="deatils">Details: <%= @product.description %></span>
      
      <br><br>

      <%= form_tag(cart_add_item_path, remote: true, method: :post, id: 'cart-form') do %>
        <%= hidden_field_tag('product_id', @product.id) %>
        <p class="radio-p">
          <label>Size </label><br>
        </p>
        <% @product.sizes.each do |size| %>
          <p class="radio-p">
            <input name="cart[size]" type="radio" id="<%= size %>" value="<%= size %>" <%= "checked" if @cart_item.size == size %>/>
            <label for="<%= size %>"><%= size %></label>
          </p>
        <% end %>
        <span class="cart-error" id="size_error"></span>
        <br><br>
        <p class="cart-form">
          <label for="delivery_date">Delivery date: </label>
          <input type="date" class="datepicker" id="delivery_date" name="cart[delivery_date]" value="<%= @cart_item.delivery_date.strftime('%e %d, %Y') rescue nil %>">
        </p>
        <span class="cart-error" id="delivery_date_error"></span>
        <br><br>
        <div class="input-field cart-form">
          <select name="cart[delivery_time]">
            <option value="" disabled selected>Choose delivery time</option>
            <option value="9 PM to 12 PM" <%= "selected" if @cart_item.delivery_time == "9 PM to 12 PM" %>>9 PM to 12 PM</option>
            <option value="12 PM to 3 PM" <%= "selected" if @cart_item.delivery_time == "12 PM to 3 PM" %>>12 PM to 3 PM</option>
            <option value="3 PM to 6 PM" <%= "selected" if @cart_item.delivery_time == "3 PM to 6 PM" %>>3 PM to 6 PM</option>
            <option value="6 PM to 9 PM" <%= "selected" if @cart_item.delivery_time == "6 PM to 9 PM" %>>6 PM to 9 PM</option>
          </select>
          <label>Delivery time</label>
        </div>
        <span class="cart-error" id="delivery_time_error"></span>
        <br><br>
        <%= submit_tag('Add to Cart', class: 'waves-effect waves-light btn') %>
      <% end %>
    </div>
  </div>
  
  <br>
  <% if user_signed_in? and current_user.admin? %>
    <div class="row center-align">
      <h3 class="center-align">Admin Actions</h3>
      <br><br>
      <div class="col s6"><%= link_to("Edit Images", edit_images_product_path, class: 'waves-effect waves-light btn') %></div>
      <div class="col s6"><%= link_to("Edit Product Details", edit_product_path, class: 'waves-effect waves-light btn') %></div>
    </div>
  <% end %>
</div>

    